[project]
name = "causal-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "altair>=6.0.0",
    "marimo>=0.19.11",
    "numpy>=2.4.2",
    "polars>=1.38.1",
    "pyzmq>=27.1.0",
    "scipy>=1.17.0",
]

[tool.marimo.formatting]
line_length = 84
